#define METHODID_CREATEPYHSICALENTITY					49

#define METHODIF_ANNOUNCEHEALING						620

#define METHODID_INVENTORYCREATE						86
#define METHODID_INVENTORYADDITEM						85
#define METHODID_INVENTORYDESTROY						87
#define METHODID_INVENTORYDISABLED						291
#define METHODID_INVENTORYMOVEFAILED					464
#define METHODID_INVENTORYMOVEITEMFAILED				465
#define METHODID_INVENTORYREMOVEITEM					88
#define METHODID_INVENTORYTRANSFER						89

#define METHODID_HOMEINVENTORY_CLOSE					79
#define METHODID_HOMEINVENTORY_DESTROYITEM				80
#define METHODID_HOMEINVENTORY_MOVEITEM					81
#define METHODID_HOMEINVENTORY_OPEN						82

#define METHODID_PERSONALINVENTORY_DESTROYITEM			127
#define METHODID_PERSONALINVENTORY_MOVEITEM				498
#define METHODID_PERSONALINVENTORY_MOVEITEMS			128
#define METHODID_PERSONALINVENTORY_SPLITITEM			499

#define METHODID_EQUIPMENTINFO							66

#define METHODID_FORCESTATE								454

#define METHODID_ENTEREDWAYPOINT						274
#define METHODID_EXITEDWAYPOINT							275
#define METHODID_SELECTWAYPOINT							178

//GAME REQUESTS
#define METHODID_REQUESTTOOLACTION						524
#define METHODID_REQUESTSWAPABILITYSLOTS				601
#define METHODID_REQUESTSWAPABILITYSLOT					522
#define METHODID_REQUESTSAVEPOSITIONINFO				162
#define METHODID_REQUESTREQUESTCORPSELOOTING			650
#define METHODID_REQUESTEQUIP							1
#define METHODID_REQUESTEQUIPARMOR						514
#define METHODID_REQUESTEQUIPWEAPON						515
#define METHODID_REQUESTFAMILYNAME						516
#define METHODID_REQUESTLOGOUT							820
#define METHODID_REQUESTLOOTALLFROMCORPSE				651
#define METHODID_REQUESTLOOTITEMFROMCORPSE				652
#define METHODID_REQUESTMAPINSTANCELIST					157
#define METHODID_REQUESTMOVEITEMTOHOMEINVENTORY			582
#define METHODID_REQUESTNPCVENDING						519
#define METHODID_REQUESTNPCVENDORPURCHASE				158
#define METHODID_REQUESTNPCVENDORSALE					159
#define METHODID_REQUESTPERFORMABILITY					33
#define METHODID_REQUESTPERFORMCHARGEDABILITY			520
#define METHODID_REQUESTPLACEOBJECT						344
#define METHODID_REQUESTPLAYERVENDORITEMSBYCATEGORY		345
#define METHODID_REQUESTPURCHASEPLAYERVENDORITEM		346
#define METHODID_REQUESTREPAIR							348
#define METHODID_REQUESTRETURNITEMTOINVENTORY			349
#define METHODID_REQUESTREVERSEENGINEER					668
#define METHODID_REQUESTSAVECURRENTCHARACTERTOPOSITION	161
#define METHODID_REQUESTTOOLTIPFORITEMTEMPLATEID		578
#define METHODID_REQUESTTOOLTIPFORITEMCLASSID			690
#define METHODID_REQUESTTOOLTIPFORCLASSID				525
#define METHODID_REQUESTTOGGLERUN						164
#define METHODID_REQUESTUNEQUIP							167
#define METHODID_REQUESTUSEOBJECT						352
#define METHODID_REQUESTUSETRANSFERCREDIT				752
#define METHODID_REQUESTVENDORBUYBACK					527
#define METHODID_REQUESTVENDORPURCHASE					528
#define METHODID_REQUESTVENDORREPAIR					667
#define METHODID_REQUESTVENDORSALE						529
#define METHODID_REQUESTVIEWPLAYERVENDOR				353
#define METHODID_REQUESTVISUALCOMBATMODE				753
#define METHODID_REQUESTWAYPOsint32LIST					168
#define METHODID_REQUESTWEAPONATTACK					354
#define METHODID_REQUESTWEAPONDRAW						530
#define METHODID_REQUESTWEAPONRELOAD					531
#define METHODID_REQUESTWEAPONSTOW						532
#define METHODID_REQUESTCHARACTERNAME					149
#define METHODID_REQUESTCREATECHARACTERINSLOT			512
#define METHODID_REQUESTDELETECHARACTERINSLOT			513
#define METHODID_REQUESTSWITCHTOCHARACTERINSLOT			523
#define METHODID_REQUESTARMWEAPON						507

//CANCEL
#define METHODID_CANCELLOGOUTREQUEST					818

#define METHODID_LOGOUTTIMEREMAINING					819

#define METHODID_HITPOsint32CHANGED						285

#define METHODID_HEAL									711

#define METHODID_CHATCHANNELJOINED						10000038
#define METHODID_LOGINOK								105
#define METHODID_SYSTEMMESSAGE							553
#define METHODID_ABILITYDRAWER							393
#define METHODID_RADIALCHAT								136
#define METHODID_SHOUT									204
#define METHODID_CHANNELCHAT							10000034
#define METHODID_WHISPER								2
#define METHODID_WHISPERSELF							241
#define METHODID_WHISPERACK								240

#define METHODID_BEGINCHARACTERSELETION					413
#define METHODID_CHARACTERCREATESUCCESS					426
#define METHODID_USERCREATIONFAILED						231
#define METHODID_CHARACTERDELETESUCCESS					734
#define METHODID_GENERATEDCHARACTERNAME					77
#define METHODID_GENERATEDFAMILYNAME					456
#define METHODID_CHARACTERUPDATEEMPTYPOD				-1 //UNK
#define METHODID_CHARACTERINFO							41
#define METHODID_WONKAVATE								242
#define METHODID_CHARACTERCLASS							40
#define METHODID_CHARACTERNAME							427
#define METHODID_CHARACTERLOGOUT						10000040

#define METHODID_ACTORNAME								16
#define METHODID_ISRUNNING								96
#define METHODID_SKILLS									548


#define METHODID_SETSKYTIME								198
#define METHODID_SETCURRENTCONTEXTID					362
#define METHODID_UPDATEREGIONS							568

#define METHODID_APPEARANCEDATA							27

#define METHODID_ATTRIBUTEINFO							29

#define METHODID_PRELOADDATA							622

#define METHODID_LEVEL									103
#define METHODID_LEVELINCREASED							104

#define METHODID_WONKAVATE								242
#define METHODID_PREWONKAVATE							134
#define METHODID_WORLDLOCATIONDESCRIPTOR				243
#define METHODID_WORLDPLACEMENTDESCRIPTOR				244

#define METHODID_DESTROYPHYSICALENTITY					56

#define METHODID_WEAPONREADY							575

#define METHODID_USE									230
#define METHODID_USEsint32ERRUPTED							609
#define METHODID_USEinterruptible						691

#define METHODID_SETAUTOLOOTTRESHOLD					546

#define METHODID_ACCEPTPARTYINVITESCHANGED				395

#define METHODID_SAVEUSEROPTIONS						694
#define METHODID_SETTARGETID							201
#define METHODID_TRASNFERCREDITTOLOCKBOX				596
#define METHODID_CLEARTRACKINGTARGET					255
#define METHODID_SETTRACKINGTARGET						202 // used by both, client and server


#define METHODID_ITEMTEMPLATETOOLTIPINFO				579

#define METHODID_MAPLOADED								107
#define METHODID_PING									129

#define METHODID_PERFORMRECOVERY						125

// Character Life/ state
#define METHODID_REVIVEME								170
#define METHODID_REVIVED								171 // not used 20120902
#define METHODID_STATECHANGE							206
#define METHODID_REQUESTREVIVE							763
#define METHODID_REVIVEREQUESTINFO						764 // not used 20120902
#define METHODID_GRAVEYARDGAINED						462
#define METHODID_PLAYERDEAD								595
#define METHODID_SWAPMESHREVIVE							552
#define METHODID_SWAPMESHDEATH							551 // not used 20120902